# Generated by Django 3.1.1 on 2020-09-18 15:09

from django.db import migrations
import server.users.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, upload_to=server.users.models.CustomUser.avatar_directory_path),
        ),
    ]
