# Generated by Django 3.1.1 on 2020-09-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200918_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
